"""
Django settings for DocuGyan project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from kombu import Queue
import dj_database_url
from datetime import timedelta
load_dotenv()


# ================== Constants variable that is used in multiple classes and in multiple files =================
TOP_K = 20
RERANK_K = 5
ENSEMBLE_WEIGHTS = [0.4, 0.6]
HISTORY_FALLBACK_SIZES = [10, 5, 2, 0]
DOWNLOAD_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    ),
    "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://www.google.com/",
    "Sec-Fetch-Dest": "image",
    "Sec-Fetch-Mode": "no-cors",
    "Sec-Fetch-Site": "cross-site",
}

ALLOWED_MIME_TYPES = {
    'image/jpeg', 'image/jpg', 'image/png', 'image/gif',
    'image/webp', 'image/svg+xml', 'image/bmp', 'image/tiff',
}





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load environment variables
SECRET_KEY = os.environ.get("SECRET_KEY")
DEBUG = os.environ.get("DEBUG","False") == "True"
VERCEL_BLOB_TOKEN = os.environ.get("BLOB_READ_WRITE_TOKEN")
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL")


ALLOWED_HOSTS = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CORS_ALLOWED_ORIGINS = [o.strip() for o in os.environ.get("CORS_ALLOWED_ORIGINS", "http://localhost:3000,https://docugyan.netlify.app").split(",") if o.strip()]
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "http://localhost:3000,https://docugyan.netlify.app").split(",") if o.strip()]
CORS_ALLOW_CREDENTIALS = True


CORS_URLS_REGEX = r'^/.*$'
SECURE_CROSS_ORIGIN_OPENER_POLICY = None



# Brevo
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "anymail.backends.sendinblue.EmailBackend")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")
ANYMAIL = {
    "SENDINBLUE_API_KEY": os.environ.get("BREVO_API_KEY"),
}

# SIGNING_KEY for JWT
SIGNING_KEY = os.environ.get("JWT_SECRET_KEY", SECRET_KEY)

# Google OAuth Client ID
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID")

# LLM API Keys
GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")
GROQ_API_KEY = os.environ.get("GROQ_API_KEY")
HUGGINGFACE_API_KEY = os.environ.get("HUGGINGFACE_API_KEY")
CEREBRAS_API_KEY = os.environ.get("CEREBRAS_API_KEY")

# LLM Backup API Keys
HUGGINGFACE_API_KEY_BACKUP = os.environ.get("HUGGINGFACE_API_KEY_BACKUP")
GROQ_API_KEY_BACKUP = os.environ.get("GROQ_API_KEY_BACKUP")
GOOGLE_API_KEY_BACKUP = os.environ.get("GOOGLE_API_KEY_BACKUP")
CEREBRAS_API_KEY_BACKUP = os.environ.get("CEREBRAS_API_KEY_BACKUP")


# --- Vector Database (Zilliz/Milvus) ---
ZILLIZ_URI = os.environ.get("ZILLIZ_URI")
ZILLIZ_TOKEN = os.environ.get("ZILLIZ_TOKEN")
ZILLIZ_ALIAS = os.environ.get("ZILLIZ_ALIAS", "default")

# -----Internet search API Keys-----
TAVILY_API_KEY = os.environ.get("TAVILY_API_KEY")

# Image search api key
SERPER_API_KEY = os.environ.get("SERPER_API_KEY")
SERPAPI_API_KEY = os.environ.get("SERPAPI_API_KEY")
GOOGLE_CX = os.environ.get("GOOGLE_CX")

# Application definition
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third Pary apps
    'rest_framework',
    'corsheaders',
    'django_celery_results',
    'channels',
    'anymail',

    # Custom apps
    'DocuAgent',
    'DocuChat',

    # Package apps
    'docu_model',
    'users',
    'core',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS_ALLOW_ALL_ORIGINS was moved up

ROOT_URLCONF = 'DocuGyan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


ASGI_APPLICATION = 'DocuGyan.asgi.application'
WSGI_APPLICATION = 'DocuGyan.wsgi.application'

# Database
DATABASES = {
    "default": dj_database_url.parse(
        os.environ.get("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=not DEBUG 
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- CACHE SETTINGS ---
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "DocuGyan-cache",
    }
}

# --- WEBSOCKET / CHANNELS SETTINGS ---
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [{"address": CELERY_BROKER_URL, "ssl": True}],
        },
    },
}

# --- CELERY SETTINGS ---
CELERY_BROKER_URL = CELERY_BROKER_URL
CELERY_RESULT_BACKEND = "django-db"
CELERY_TASK_IGNORE_RESULT = False 

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json' 
CELERY_TIMEZONE = "Asia/Kolkata"
CELERY_ENABLE_UTC = True
# Add after CELERY_BROKER_URL line at the top
CELERY_BROKER_USE_SSL = {"ssl_cert_reqs": None}
CELERY_REDIS_BACKEND_USE_SSL = {"ssl_cert_reqs": None}


# --- QUEUE & ROUTING CONFIGURATION ---
CELERY_TASK_DEFAULT_QUEUE = "DocuGyan"

CELERY_QUEUES = (
    Queue('DocuGyan', routing_key='task.default'),
    Queue('DocuAgent_tasks', routing_key='task.DocuAgent_tasks'),
    Queue('DocuChat_tasks', routing_key='task.DocuChat_tasks'),
    Queue('DocuMail_tasks', routing_key='task.DocuMail_tasks'),
)

CELERY_TASK_ROUTES = {

    # Heavy AI tasks
    'DocuAgent.tasks.*': {
        'queue': 'DocuAgent_tasks',
        'routing_key': 'task.DocuAgent_tasks'
    },

    # Real-time chat tasks
    'DocuChat.tasks.*': {
        'queue': 'DocuChat_tasks',
        'routing_key': 'task.DocuChat_tasks'
    },

    # Email tasks
    'DocuMail.tasks.*': {
        'queue': 'DocuMail_tasks',
        'routing_key': 'task.DocuMail_tasks'
    },
}

# --- WORKER OPTIMIZATION SETTINGS ---
CELERY_WORKER_CONCURRENCY = 2 
CELERY_WORKER_AUTOSCALE = (4, 2)   # was (4, 2)
CELERY_BROKER_POOL_LIMIT = 5       # was 2
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_ACKS_LATE = True
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,
    'socket_timeout': 30,
    'socket_connect_timeout': 30,
    'retry_on_timeout': True,
}

AUTH_USER_MODEL = 'docu_model.CustomUser'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'SIGNING_KEY': SIGNING_KEY, 
    'AUTH_COOKIE': 'access',
    'AUTH_COOKIE_REFRESH': 'refresh',
    'USER_ID_FIELD': 'user_uuid',  
    'USER_ID_CLAIM': 'user_uuid',  
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'core.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '100000/day',
        'anon': '10000/day',
    },
}



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} [{name}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # Your apps
        'DocuChat': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        # Silence the "messy" libraries
        'pymilvus': {'level': 'WARNING', 'handlers': ['console'], 'propagate': False},
        'openai': {'level': 'WARNING', 'handlers': ['console'], 'propagate': False},
        'langchain': {'level': 'INFO', 'handlers': ['console'], 'propagate': False},
    },
}





