"""
Django settings for DocuGyan project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from kombu import Queue
import dj_database_url
from datetime import timedelta
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load environment variables
SECRET_KEY = os.environ.get("SECRET_KEY")
DEBUG = os.environ.get("DEBUG","False") == "True"
BLOB_READ_WRITE_TOKEN = os.environ.get("BLOB_READ_WRITE_TOKEN")
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL")


ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "127.0.0.1").split(",")
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")

# Brevo
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "anymail.backends.sendinblue.EmailBackend")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")
ANYMAIL = {
    "SENDINBLUE_API_KEY": os.environ.get("BREVO_API_KEY"),
}

# SIGNING_KEY for JWT
SIGNING_KEY = os.environ.get("JWT_SECRET_KEY", SECRET_KEY)

# Google OAuth Client ID
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID")


# Application definition
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third Pary apps
    'rest_framework',
    'corsheaders',
    'django_celery_results',
    'channels',
    'anymail',

    # Custom apps
    'DocuAgent',
    'DocuChat',

    # Package apps
    'docu_model',
    'users',
    'core',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'DocuGyan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


ASGI_APPLICATION = 'DocuGyan.asgi.application'


# Database
DATABASES = {
    "default": dj_database_url.parse(
        os.environ.get("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- CACHE SETTINGS ---
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "DocuGyan-cache",
    }
}

# --- WEBSOCKET / CHANNELS SETTINGS ---
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [CELERY_BROKER_URL],
        },
    },
}



# --- CELERY SETTINGS ---
CELERY_BROKER_URL = CELERY_BROKER_URL
CELERY_RESULT_BACKEND = None

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json' 
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True
CELERY_TASK_IGNORE_RESULT = True

# --- QUEUE & ROUTING CONFIGURATION ---
CELERY_TASK_DEFAULT_QUEUE = "DocuGyan"

CELERY_QUEUES = (
    Queue('DocuGyan', routing_key='task.default'),
    Queue('DocuAgent_tasks', routing_key='task.DocuAgent_tasks'),
    Queue('DocuChat_tasks', routing_key='task.DocuChat_tasks'),
    Queue('DocuMail_tasks', routing_key='task.DocuMail_tasks'),
)

CELERY_TASK_ROUTES = {

    # Heavy AI tasks
    'DocuAgent.tasks.*': {
        'queue': 'DocuAgent_tasks',
        'routing_key': 'task.DocuAgent_tasks'
    },

    # Real-time chat tasks
    'DocuChat.tasks.*': {
        'queue': 'DocuChat_tasks',
        'routing_key': 'task.DocuChat_tasks'
    },

    # Email tasks
    'DocuMail.tasks.*': {
        'queue': 'DocuMail_tasks',
        'routing_key': 'task.DocuMail_tasks'
    },
}

# --- WORKER OPTIMIZATION SETTINGS ---
CELERY_WORKER_CONCURRENCY = 5  
CELERY_WORKER_AUTOSCALE = (12, 6)  
CELERY_BROKER_POOL_LIMIT = 5
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_ACKS_LATE = True
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True


AUTH_USER_MODEL = 'docu_model.CustomUser'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'SIGNING_KEY': SIGNING_KEY, 
    'AUTH_COOKIE': 'access',
    'AUTH_COOKIE_REFRESH': 'refresh',
    'USER_ID_FIELD': 'user_uuid',  
    'USER_ID_CLAIM': 'user_uuid',  
}
